### ISSUE TITLE
Support for JDK 17 needed for cloudevents library

### ISSUE THREAD

**Issue by akchamps** [cloudevents/sdk-java#563] opened 2023-05-04 04:23 UTC
We are using cloudevents library with JDK 8. However, we are not able to upgrade our project to JDK 17 due to dependency on cloudevents. Following issue is encountered while doing so,
`java.lang.NoClassDefFoundError: javax/validation/Validation
        at io.cloudevents.v1.CloudEventBuilder.getValidator(CloudEventBuilder.java:56)
        at io.cloudevents.v1.CloudEventBuilder.build(CloudEventBuilder.java:141)`

**Comment by pierDipi** [comment] 2023-05-04 06:54
I'm using JDK 17 in project just fine and we're running tests on [JDK 17](https://github.com/cloudevents/sdk-java/blob/4ebeab0e0ff8d0c507c47b32dd7ec2da95dc87cb/.github/workflows/pr.yaml#L15)

**Comment by pierDipi** [comment] 2023-05-15 15:31
@akchamps can you provide a reproducer?

**Comment by pierDipi** [comment] 2023-07-27 09:23
@akchamps any updates on this?

**Comment by habutre** [comment] 2023-08-10 20:45
I am facing the same issue, the simplest code that make it breaks is

```
@Test
  void testMyCloudEventHandler() {
    var cloudEvent =
        CloudEventBuilder.<ClientCreated>builder()
            .withId("eventId")
            .withSource(URI.create("source"))
            .withType("type")
            .build();

    myEventHandler.handle(cloudEvent);

  verify(foo).bar();
}
```

The error:

```
java.lang.NoClassDefFoundError: javax/validation/Validation

	at io.cloudevents.v1.CloudEventBuilder.getValidator(CloudEventBuilder.java:56)
	at io.cloudevents.v1.CloudEventBuilder.build(CloudEventBuilder.java:141)
	(...suppressed lines...)
Caused by: java.lang.ClassNotFoundException: javax.validation.Validation
	... 71 more
```

**Comment by pierDipi** [comment] 2023-08-23 15:51
@habutre I see, you're using version 1.3, which is [3+ years old](https://github.com/cloudevents/sdk-java/releases/tag/v1.3.0) and Java 17 wasn't released at that time, can you upgrading to a v2 version, possibly the latest one 2.5.0?

**Comment by habutre** [comment] 2023-08-23 20:57
@pierDipi  yes I am aware of it, but not all business can be changed in the speed of light. Some hard constraints or compliance rules may slow down the migration process heavily. I would be really happy to make this upgrade if it rely only on me or my team.

A PR would be acceptable in your POV or patches are frozen?

**Comment by pierDipi** [comment] 2023-08-24 08:30
yes, contributions are very welcome, some notes: I took over SDK maintenance after v2 and I'm not that familiar with v1, so I'd generally say, if the patch / fix is small and it is _not_ a breaking change (because it would require a major version bump, which exist already), we can consider it

**Comment by habutre** [comment] 2023-09-01 18:08
Thanks for your point @pierDipi actually it makes more sense to me now

In the end the issue was caused by upgrading to Springboot 3.x rather moving to JDK 17, in case someone faces the same in the future maybe helps to indicate that we solve adding two deps like below:

```
<dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
      <version>${hibernate-validator.version}</version>
  </dependency>
  <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
      <version>${validation-api.version}</version>
  </dependency>
```

IMO this issue can be closed

**Comment by pierDipi** [comment] 2023-10-02 08:12
Thanks for the update @habutre, I'm closing this issue for now

**Closed by pierDipi** 2023-10-02 08:12 UTC
Labels: needs-user-input
