### ISSUE TITLE
NullPointerException deserializing structured event

### ISSUE THREAD

**Issue by wkennedy** [cloudevents/sdk-java#283] opened 2020-11-17 15:32 UTC
Found in 2.0.0-milestone4. When attempting to deserialize a cloud event consumed via a Kafka consumer.

Caused by: java.lang.NullPointerException: Cannot invoke "io.cloudevents.rw.CloudEventDataMapper.map(io.cloudevents.CloudEventData)" because "mapper" is null
	at io.cloudevents.jackson.JsonFormat.deserialize(JsonFormat.java:95)
	at io.cloudevents.core.message.MessageReader.lambda$toEvent$0(MessageReader.java:124)
	at io.cloudevents.core.message.impl.GenericStructuredMessageReader.read(GenericStructuredMessageReader.java:39)
	at io.cloudevents.core.message.MessageReader.toEvent(MessageReader.java:124)
	at io.cloudevents.core.message.MessageReader.toEvent(MessageReader.java:109)
	at io.cloudevents.kafka.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:59)
	at io.cloudevents.kafka.CloudEventDeserializer.deserialize(CloudEventDeserializer.java:34)

For an example please see unit test here:

https://github.com/wkennedy/spring-kafka-cloud-events/tree/cloudevents-2.0.0-milestone4

StructuredCloudEventsTest -> testCloudEventsStructuredMessageConverter

**Comment by slinkydeveloper** [comment] 2020-11-17 15:37
I guess it's a duplicate of https://github.com/cloudevents/sdk-java/pull/259, reopen if you need it

**Closed by slinkydeveloper** 2020-11-17 15:37 UTC

**Comment by wkennedy** [comment] 2020-11-17 16:01
Confirmed it's fixed in the latest snapshot.

**Comment by slinkydeveloper** [comment] 2020-11-17 16:14
Cool, we're going to release this soon
