### ISSUE TITLE
JSON Format - Behavior when non spec-compliant

### ISSUE THREAD

**Issue by JemDay** [cloudevents/sdk-java#360] opened 2021-03-17 22:23 UTC
What should the behavior of the JSON Format be when it receives a JSON document that is not spec-compliant, eg receives a context attribute (or extension) that is a 'Number' but not an 'Integer'.

Options :
- Ignore,
- translate to a 'String'

Raised as a result of Issue #358

**Comment by slinkydeveloper** [comment] 2021-03-18 11:23
I think by default the conversion should fail, IMO it's the expected behaviour. Maybe, in future, we could have a _less strict_ mode where we translate to `String`?

**Comment by slinkydeveloper** [comment] 2021-04-28 13:47
Is there something to do here @JemDay?

**Comment by JemDay** [comment] 2021-04-28 18:46
I forgot about this one ... I believe the other PR does cover the numeric use-cases .. but I'm not sure I checked any of the other variants..

**Comment by slinkydeveloper** [comment] 2021-04-28 19:36
Ok, since this one seems specific to the integer/number problem, I'm going to close it. Feel free to reopen if you need it.

As a rule of thumb, because I think this is a _reference implementation_ of the spec, I think we should reject when receiving invalid events, more than attempting to fix/fit them. Given that, nothing prevents us in the future to design a more _permissive_ parsing mode, although I personally don't have specific ideas about it :smile:.

**Closed by slinkydeveloper** 2021-04-28 19:36 UTC
Labels: question
