### ISSUE TITLE
Deserialize cloud event mode STRUCTURE failed with JsonFormat

### ISSUE THREAD

**Issue by yeudit** [cloudevents/sdk-java#297] opened 2020-11-23 18:44 UTC
I'm using CloudEventDeserializer with config:

```java
Map<String, Object> ceConfigs = new HashMap<>();
ceConfigs.put(ENCODING_CONFIG, Encoding.STRUCTURED);
ceConfigs.put(EVENT_FORMAT_CONFIG, JsonFormat.CONTENT_TYPE);
CloudEventDeserializer cloudEventDeserializer = new CloudEventDeserializer();
cloudEventDeserializer.configure(ceDeserializerConfigs, false);
```

when I'm calling cloudEventDeserializer.deserialize()
it failed with NullPointerException here: https://github.com/cloudevents/sdk-java/blob/master/formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java#L96

because there is no mapper config in the cloudEventDeserializer object.

I think the fix should be in this line: https://github.com/cloudevents/sdk-java/blob/master/core/src/main/java/io/cloudevents/core/message/MessageReader.java#L106
```java
default CloudEvent toEvent(CloudEventDataMapper<? extends CloudEventData> mapper) throws CloudEventRWException, IllegalStateException {
        switch (getEncoding()) {
            case BINARY:
                return CloudEventUtils.toEvent(this, mapper);
            case STRUCTURED:
                return this.read((format, value) -> format.deserialize(value, mapper));
            default:
                throw new IllegalStateException("Unknown encoding");
        }
    }
```
instead of
`return this.read((format, value) -> format.deserialize(value, mapper));`
check the mapper and call the correct method:
`return this.read((format, value) -> mapper == null ? format.deserialize(value, mapper) : format.deserialize(value));`

Thanks!

**Comment by slinkydeveloper** [comment] 2020-11-23 19:21
Duplicate of https://github.com/cloudevents/sdk-java/issues/285, this is fixed in the upcoming release

**Closed by slinkydeveloper** 2020-11-23 19:21 UTC
